dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng lint
  - ng test --single-run --code-coverage
  - codecov -f coverage/*.json
